name: "Prod Terraform Workflow"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main      

permissions:
  id-token: write
  contents: read
  
jobs: 
  terraform-init-plan:
    runs-on: self-hosted
    steps: 
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 3a74994d-83ee-4f0e-8e37-271effc1ddf0
          tenant-id: c83b7e7f-8a37-4a58-b3cc-83a0b39033d0
          subscription-id: 3130fe23-dc28-48ba-a8e3-43702c2970a2
            
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: environments/prod
        
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: environments/prod

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: environments/prod        
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: environments/prod    
        
  terraform-apply:    
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    needs: terraform-init-plan
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 3a74994d-83ee-4f0e-8e37-271effc1ddf0
          tenant-id: c83b7e7f-8a37-4a58-b3cc-83a0b39033d0
          subscription-id: 3130fe23-dc28-48ba-a8e3-43702c2970a2
          
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: environments/prod

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        continue-on-error: true
        working-directory: environments/prod              
          
